### ISSUE TITLE
Only the first 100 models are returned by the server

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-api#5]
### What happened?

If a course has more than 100 models the server will only return the first 100 and not indicate that there is more data. The `X-Adapt-PageTotal` header only indicates 1 page.

### Expected behaviour

`X-Adapt-PageTotal` should indicate to the client how many pages of data there are.

### Steps to reproduce

Create a course with more than 100 models and inspect the /api/content/query headers. I can provide an example course with more than 100 models if required.

### Authoring tool version

master

**Comment by chris-steele** [comment]
Tagging as high priority because this might become a fairly common problem: if you have, say, a 5/6 page course each page with a dozen or so components there is a good chance there will be more than 100 models.

**Comment by chris-steele** [comment]
@taylortom just noticed this was moved to the backlog. The way this problem manifests in the UI is some content is missing and can't be edited. Do you think we should prioritise?

**Comment by taylortom** [comment]
This one should be fixed (in master of adapt-authoring-api)

**Comment by chris-steele** [comment]
About to test with adapt-authoring-ui master, but noticed a problem with no-sidebar. Once 100 models are reached a runtime error occurs:

![image](https://github.com/adapt-security/adapt-authoring-api/assets/1228225/9af1ef65-69f2-4896-881f-b130009488cb)

`Link` is `</api/content/query?per_page=100&per_page=100&page=1>; rel="first", </api/content/query?per_page=100&per_page=100&page=1>; rel="prev"'` but code is expecting `rel="next"` to be present.

Issue seems to relate to [differences ](https://github.com/adapt-security/adapt-authoring-ui/compare/master..no-sidebar#diff-75325d3967e2d978d523c77fee5da12597dacb48f9e3d926d3a2e04959255e48L37)in the fetch method.

**Comment by taylortom** [comment]
@joe-allen-89/@chris-steele what's the status of this one? If it's only related to v1.1 code, I'll label it appropriately and pop it back in the backlog

**Comment by joe-allen-89** [comment]
@taylortom the regular expression change in this pr - https://github.com/adapt-security/adapt-authoring-ui/pull/276 will fix this as it's returning all models, just needs a good test.

**Comment by chris-steele** [comment]
I applied the fix you mention @joe-allen-89 (https://github.com/adapt-security/adapt-authoring-ui/pull/276) but this does not seem to fix the problem. Are there any other fixes you know of that may also be required?

**Comment by joe-allen-89** [comment]
Tested with standard no-sidebar branch and it's returning all 412 models in my test course, @chris-steele has tested with new build process+clipboard+multilang branch, which needs further investigation as to what else has changed since.

**Comment by chris-steele** [comment]
thanks @joe-allen-89 I'll try to find out what the problem is

**Comment by chris-steele** [comment]
Working on this

**Comment by joe-allen-89** [comment]
Thank you for checking that branch @chris-steele
